  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: konga-postgres-pvc
    namespace: egs-uniride
  spec:
    accessModes:
      - ReadWriteMany
    storageClassName: longhorn
    resources:
      requests:
        storage: 100Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga-postgres
  namespace: egs-uniride
spec:
  selector:
    matchLabels:
      app: konga-postgres
  template:
    metadata:
      labels:
        app: konga-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: konga
            - name: POSTGRES_USER
              value: your-db-username
            - name: POSTGRES_PASSWORD
              value: your-db-password
          volumeMounts:
            - name: konga-postgres-data
              mountPath: /var/lib/postgresql
      volumes:
        - name: konga-postgres-data
          persistentVolumeClaim:
            claimName: konga-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: konga-postgres-service
  namespace: egs-uniride
spec:
  selector:
    app: konga-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP