apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga
  namespace: egs-uniride
spec:
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        app: konga
    spec:
      containers:
        - name: konga
          image: pantsel/konga:latest
          ports:
            - containerPort: 1337
          env:
            - name: DB_ADAPTER
              value: postgres
            - name: DB_HOST
              value: konga
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: your-db-username
            - name: DB_PASSWORD
              value: your-db-password
            - name: DB_DATABASE
              value: konga
            #- name: NODE_PG_FORCE_NATIVE
            #  value: "1"
          volumeMounts:
          - name: konga-postgres-data
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: konga-postgres-data
        persistentVolumeClaim:
          claimName: konga-postgres-pvc

---
apiVersion: batch/v1
kind: Job
metadata:
  name: auth-api-job
  namespace: egs-uniride
spec:
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kong-migrations
          image: kong
          env:
            - name: KONG_DATABASE
              value: postgres
            - name: KONG_PG_HOST
              value: 127.0.0.1
            - name: POSTGRES_DB
              value: konga
            - name: KONG_USER
              value: your-db-username
            - name: KONG_PG_PASSWORD
              value: your-db-password
            - name: KONG_CASSANDRA_CONTACT_POINTS
              value: kong-database
            - name: KONG_PG_PORT
              value: "5432"
          command: ["kong","migrations","bootstrap"]
      volumes:
        - name: konga-postgres-data
          persistentVolumeClaim:
            claimName: konga-postgres-pvc
