apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: konga-postgres-pvc
  namespace: egs-uniride
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi