apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db-data-kong-postgres
  name: db-data-kong-postgres
  namespace: egs-uniride
spec:
  volumeMode: Filesystem
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
